# Generated by Django 3.1.3 on 2020-12-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Users',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'All_Users',
            },
        ),
    ]
