# Generated by Django 3.1.3 on 2020-12-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='all_users',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
