# Generated by Django 3.1.3 on 2020-11-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='webuser',
            name='login_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
