# Generated by Django 3.1.3 on 2020-12-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_for_dbwork2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast_record',
            name='broadcast_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campus_life',
            name='created_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campus_life',
            name='life_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course_info',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course_info',
            name='provided_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='favorite_record',
            name='favorite_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favorite_record',
            name='favorite_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='focus_record',
            name='focus_record_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='focus_record',
            name='focus_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='major_in_system',
            name='major_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommend_item',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommend_item_major',
            name='item_major_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommend_item_route',
            name='item_route_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resource_book',
            name='resource_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resource_web',
            name='resource_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='study_field',
            name='study_field_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='teacher_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
