# Generated by Django 3.1.3 on 2020-12-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_for_dbwork2', '0003_recommend_item_major_major_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_item_major',
            name='major_title',
            field=models.TextField(),
        ),
    ]
