# Generated by Django 3.1.3 on 2020-12-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_for_dbwork2', '0004_auto_20201213_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend_item_route',
            name='hot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommend_item_route',
            name='watch',
            field=models.IntegerField(default=0),
        ),
    ]
