# Generated by Django 3.1.3 on 2020-12-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_for_dbwork2', '0006_auto_20201213_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_major',
            field=models.CharField(max_length=100),
        ),
    ]
