# Generated by Django 3.1.3 on 2020-12-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_for_dbwork2', '0007_auto_20201213_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast_record',
            name='broadcast_time',
            field=models.DateField(),
        ),
    ]
