# Generated by Django 3.1.3 on 2020-12-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_for_dbwork2', '0008_auto_20201213_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_sequence',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
