# Generated by Django 3.1.3 on 2020-12-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_for_dbwork2', '0009_auto_20201213_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_sequence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
