# Generated by Django 3.1.3 on 2020-12-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_for_dbwork2', '0010_auto_20201213_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_Num',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Grade_Num',
            },
        ),
    ]
