# Generated by Django 3.1.3 on 2020-12-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_for_dbwork2', '0011_grade_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus_life',
            name='label',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
